# Generated by Django 4.1.2 on 2022-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='photo',
            field=models.ImageField(blank=True, default='photo.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Системные требования'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='details',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
